global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - '116.203.19.212:9093'
            - '5.161.191.69:9093'
            - '176.74.218.108'
rule_files:
  - '/etc/prometheus/rules/*.yml'

scrape_configs:

  # Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - '127.0.0.1:9090'
        labels:
          server: 'Monitoring-Server'

  # Node Exporter
  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - '116.203.19.212:9101'
        labels:
          server: 'Telyo'

      - targets:
          - '5.161.191.69:9101'
        labels:
          server: 'Web iCallify'

      - targets:
          - '176.74.218.108:9101'
        labels:
          server: 'VX-Telecom'

      - targets:
          - '138.199.196.14:9101'
        labels:
          server: 'Nathan'

      - targets:
          - '138.199.158.109:9101'
        labels:
          server: 'IT-SKY'

      - targets:
          - '102.223.38.125:9101'
        labels:
          server: 'Ifeany'

  # Nginx Exporter
  - job_name: 'nginx_exporter'
    static_configs:
      - targets:
          - '116.203.19.212:9113'
        labels:
          server: 'Telyo'

      - targets:
          - '5.161.191.69:9113'
        labels:
          server: 'Web iCallify'

      - targets:
          - '176.74.218.108:9113'
        labels:
          server: 'VX-Telecom'

      - targets:
          - '138.199.196.14:9113'
        labels:
          server: 'Nathan'

      - targets:
          - '138.199.158.109:9113'
        labels:
          server: 'IT-SKY'

      - targets:
          - '102.223.38.125:9113'
        labels:
          server: 'Ifeany'

  # Redis Exporter
  - job_name: 'redis_exporter'
    static_configs:
      - targets:
          - '116.203.19.212:9104'
        labels:
          server: 'Telyo'

      - targets:
          - '5.161.191.69:9104'
        labels:
          server: 'Web iCallify'

      - targets:
          - '176.74.218.108:9104'
        labels:
          server: 'VX-Telecom'

      - targets:
          - '138.199.196.14:9104'
        labels:
          server: 'Nathan'

      - targets:
          - '138.199.158.109:9104'
        labels:
          server: 'IT-SKY'

      - targets:
          - '102.223.38.125:9104'
        labels:
          server: 'Ifeany'

  # FreeSWITCH Exporter
  - job_name: 'freeswitch_exporter'
    static_configs:
      - targets:
          - '116.203.19.212:9282'
        labels:
          server: 'Telyo'

      - targets:
          - '5.161.191.69:9282'
        labels:
          server: 'Web iCallify'

      - targets:
          - '176.74.218.108:9282'
        labels:
          server: 'VX-Telecom'

      - targets:
          - '138.199.196.14:9282'
        labels:
          server: 'Nathan'

      - targets:
          - '138.199.158.109:9282'
        labels:
          server: 'IT-SKY'

      - targets:
          - '102.223.38.125:9282'
        labels:
          server: 'Ifeany'

  # MongoDB Exporter
  - job_name: 'mongodb_exporter'
    static_configs:
      - targets:
          - '116.203.19.212:9216'
        labels:
          server: 'Telyo'

      - targets:
          - '5.161.191.69:9216'
        labels:
          server: 'Web iCallify'

      - targets:
          - '176.74.218.108:9216'
        labels:
          server: 'VX-Telecom'
      
      - targets:
          - '138.199.196.14:9216'
        labels:
          server: 'Nathan'

      - targets:
          - '138.199.158.109:9216'
        labels:
          server: 'IT-SKY'

      - targets:
          - '102.223.38.125:9216'
        labels:
          server: 'Ifeany'

  # Blackbox ICMP
  - job_name: 'icmp'
    metrics_path: /probe

    params:
      module:
        - icmp_check

    static_configs:
      - targets:
          - '116.203.19.212'
        labels:
          server: 'Telyo'

      - targets:
          - '5.161.191.69'
        labels:
          server: 'Web iCallify'

      - targets:
          - '176.74.218.108'
        labels:
          server: 'VX-Telecom'

      - targets:
          - '138.199.196.14'
        labels:
          server: 'Nathan'

      - targets:
          - '138.199.158.109'
        labels:
          server: 'IT-SKY'

      - targets:
          - '102.223.38.125'
        labels:
          server: 'Ifeany'

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target

      - source_labels: [__param_target]
        target_label: target

      - target_label: __address__
        replacement: '127.0.0.1:9115'
